In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

import os
os.chdir(r"C:\Users\Excalibur\Desktop\VERİ BİLİMİ\Makine Öğrenmesi\verisetleri")

In [2]:
df = pd.read_excel("kredi_veriseti.xlsx")

In [3]:
df.head()

cinsiyet  yas  maas  kredi
0    Erkek   22  2200      0
1    Erkek   38  2300      0
2    Kadın   29  4600      0
3    Kadın   30  6000      0
4    Erkek   22  7900      0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   cinsiyet  400 non-null    object
 1   yas       400 non-null    int64 
 2   maas      400 non-null    int64 
 3   kredi     400 non-null    int64 
dtypes: int64(3), object(1)
memory usage: 12.6+ KB


### ONE HOT ENCODING

In [7]:
one_hot = OneHotEncoder(handle_unknown="ignore")
# handle_unknown="ignore" : bilinmeyen bir değer geldiğinde umursama diyoruz.

one_hot_cinsiyet = one_hot.fit_transform(df.cinsiyet.values.reshape(-1,1)).toarray()
# toarray() : numpy array dizisine çeviriyoruz.

In [10]:
one_hot.categories_

[array(['Erkek', 'Kadın'], dtype=object)]

In [9]:
one_hot_cinsiyet  # 1 sütun erkek, 2.sütun kadın

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.

In [11]:
one_hot_df = pd.DataFrame(one_hot_cinsiyet, columns= one_hot.categories_)

In [12]:
one_hot_df

Erkek Kadın
0     1.0   0.0
1     1.0   0.0
2     0.0   1.0
3     0.0   1.0
4     1.0   0.0
..    ...   ...
395   0.0   1.0
396   1.0   0.0
397   0.0   1.0
398   1.0   0.0
399   0.0   1.0

[400 rows x 2 columns]

In [14]:
df2 = df.join(one_hot_df)
df2.head()

cinsiyet  yas  maas  kredi  (Erkek,)  (Kadın,)
0    Erkek   22  2200      0       1.0       0.0
1    Erkek   38  2300      0       1.0       0.0
2    Kadın   29  4600      0       0.0       1.0
3    Kadın   30  6000      0       0.0       1.0
4    Erkek   22  7900      0       1.0       0.0

In [15]:
df2.drop("cinsiyet", axis=1, inplace=True)
df2.head()

yas  maas  kredi  (Erkek,)  (Kadın,)
0   22  2200      0       1.0       0.0
1   38  2300      0       1.0       0.0
2   29  4600      0       0.0       1.0
3   30  6000      0       0.0       1.0
4   22  7900      0       1.0       0.0

In [16]:
X = df2.drop("kredi",axis=1)
y = df2.kredi

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size = 0.33,
                                                    random_state = 42)

In [19]:
X_train # verisetinden rastgele %33 lük bir alanı aldı

yas   maas  (Erkek,)  (Kadın,)
258   61   9800       0.0       1.0
177   28   2500       1.0       0.0
119   44   6200       1.0       0.0
194   31   9200       1.0       0.0
229   45   8300       0.0       1.0
..   ...    ...       ...       ...
71    27   3000       0.0       1.0
106   29   3800       0.0       1.0
270   46  13600       0.0       1.0
348   42   8000       1.0       0.0
102   35   8900       0.0       1.0

[268 rows x 4 columns]

**Ölçeklendirme**

In [20]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [21]:
sc = StandardScaler()

In [22]:
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

**Modelleme Aşaması**

In [23]:
model = LogisticRegression(random_state=0)
model.fit(X_train, y_train) # eğitimi gerçekleştirdik

LogisticRegression(random_state=0)

**Tahmin Sonuçları**

In [24]:
y_pred = model.predict(X_test)
y_pred

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0],
      dtype=int64)

In [25]:
y_test.values

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0],
      dtype=int64)

**Performans Değerlendirmesi**

In [30]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
# sınıflandırmada performans değerlendirmelerinde kullanılan metriklerdir.
# accuracy_score : doğruluk skoru yüzde verir. ne kadarını doğru bildik.

In [27]:
confusion_matrix(y_true = y_test, y_pred = y_pred)

array([[78,  2],
       [19, 33]], dtype=int64)

* 78 ve 33 doğru tahminler
* 19 ve 2 yanlış tahminlerdir.

In [29]:
classification_report(y_true = y_test, y_pred = y_pred)

'              precision    recall  f1-score   support\n\n           0       0.80      0.97      0.88        80\n           1       0.94      0.63      0.76        52\n\n    accuracy                           0.84       132\n   macro avg       0.87      0.80      0.82       132\nweighted avg       0.86      0.84      0.83       132\n'

In [31]:
accuracy_score(y_true = y_test, y_pred = y_pred) # %84 oranında kredi verilip verilmediğini tahmin etmiş olduk

0.8409090909090909